# Generated by Django 5.0.1 on 2026-01-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Short description displayed on cards."),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Project screenshot or mockup.", upload_to="projects/"
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True, help_text="Link to the live project or repo."
                    ),
                ),
                (
                    "case_study_link",
                    models.URLField(
                        blank=True, help_text="Link to a detailed case study."
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on the homepage."
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of display (lower numbers first)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
