# Generated by Django 5.0.1 on 2025-12-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique category name (max 100 characters)', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name (auto-generated if empty)', max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Optional category description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx'), models.Index(fields=['name'], name='blog_catego_name_cb8828_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique tag name (max 50 characters)', max_length=50, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='blog_tag_slug_915fc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title (max 200 characters)', max_length=200, verbose_name='Post Title')),
                ('slug', models.SlugField(help_text='URL-friendly version of title (must be unique)', max_length=200, unique=True, verbose_name='URL Slug')),
                ('content', models.TextField(help_text='Main post content (supports Markdown in future)', verbose_name='Post Content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary (max 500 characters, auto-generated if empty)', max_length=500, verbose_name='Excerpt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Post publication status', max_length=10, verbose_name='Status')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional featured image (uploaded to media/blog/featured/YYYY/MM/)', null=True, upload_to='blog/featured/%Y/%m/', verbose_name='Featured Image')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters, auto-generated if empty)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated (max 255 characters)', max_length=255, verbose_name='Meta Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date/time when post was published (auto-set on first publish)', null=True, verbose_name='Published At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text="Commenter's name", max_length=100, verbose_name='Name')),
                ('author_email', models.EmailField(help_text="Commenter's email (not displayed publicly)", max_length=254, verbose_name='Email')),
                ('author_url', models.URLField(blank=True, help_text='Optional website URL', verbose_name='Website')),
                ('content', models.TextField(help_text='Comment content', verbose_name='Comment')),
                ('is_approved', models.BooleanField(default=False, help_text='Approve comment for public display', verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Commenter's IP address (for moderation)", null=True, verbose_name='IP Address')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'is_approved', '-created_at'], name='blog_commen_post_id_1f15d9_idx'), models.Index(fields=['is_approved'], name='blog_commen_is_appr_be38d5_idx'), models.Index(fields=['-created_at'], name='blog_commen_created_1f5393_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status'], name='blog_post_author__95cbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='blog_post_publish_2c9212_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'published'])), name='valid_post_status'),
        ),
    ]
