# Generated by Django 5.0.1 on 2025-12-22 18:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Main post content with rich text editor', verbose_name='Post Content'),
        ),
    ]
