# Generated by Django 5.0.1 on 2026-02-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_markdown",
            field=models.TextField(
                blank=True,
                help_text="Primary authoring field. Markdown will be converted to sanitized HTML automatically.",
                verbose_name="Post Content (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO title (recommended up to 60 characters, auto-generated from title if empty)",
                max_length=60,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Rendered/sanitized HTML for frontend output. Filled automatically from Markdown when provided.",
                verbose_name="Post Content",
            ),
        ),
    ]
