# Generated by Django 5.0.1 on 2026-02-08 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_content_markdown_post_meta_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image_focus_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Horizontal crop focus from left (0) to right (100).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Image Focus X (%)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image_focus_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Vertical crop focus from top (0) to bottom (100).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Image Focus Y (%)",
            ),
        ),
    ]
