# Generated by Django 5.0.1 on 2026-09-21 09:23

from django.db import migrations, models

from config.text import html_to_text, markup_to_text, truncate_text


def normalize_summaries(apps, schema_editor):
    """Rewrite existing excerpt/meta_description as plain text (see Post.save)."""
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.only("pk", "content", "excerpt", "meta_description").iterator():
        excerpt = truncate_text(
            markup_to_text(post.excerpt) or html_to_text(post.content), 500
        )
        meta_description = truncate_text(
            markup_to_text(post.meta_description) or excerpt, 160
        )
        if excerpt != post.excerpt or meta_description != post.meta_description:
            Post.objects.filter(pk=post.pk).update(
                excerpt=excerpt, meta_description=meta_description
            )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_featured_image_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Plain-text summary for cards (max 500 characters). HTML/Markdown is stripped on save; auto-generated from content if empty.', max_length=500, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description, plain text (max 160 characters). HTML/Markdown is stripped on save; auto-generated from excerpt if empty.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.RunPython(normalize_summaries, migrations.RunPython.noop),
    ]
