# Generated by Django 5.0.1 on 2025-12-23 11:13

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name (max 200 characters)', max_length=200, verbose_name='Full Name')),
                ('title', models.CharField(help_text='Professional title/headline (max 300 characters)', max_length=300, verbose_name='Professional Title')),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, verbose_name='Email Address')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', verbose_name='LinkedIn URL')),
                ('location', models.CharField(blank=True, help_text='Current location (city, country)', max_length=200, verbose_name='Location')),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(help_text='Professional summary and key highlights', verbose_name='Professional Summary')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo (optional, uploaded to media/resume/photos/)', null=True, upload_to='resume/photos/', verbose_name='Profile Photo')),
                ('is_active', models.BooleanField(default=True, help_text='Set active profile (only one profile should be active)', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-is_active', '-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='resume_prof_is_acti_842131_idx')],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Job position/role title (max 200 characters)', max_length=200, verbose_name='Position Title')),
                ('company', models.CharField(help_text='Company/organization name (max 200 characters)', max_length=200, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, help_text='Job location (city, country)', max_length=200, verbose_name='Location')),
                ('start_date', models.DateField(help_text='Employment start date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Employment end date (leave empty for current position)', null=True, verbose_name='End Date')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Job responsibilities and achievements', verbose_name='Description')),
                ('company_description', models.TextField(blank=True, help_text='Brief company description (optional)', verbose_name='Company Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resume.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-start_date'],
                'indexes': [models.Index(fields=['profile', 'order'], name='resume_expe_profile_55468b_idx'), models.Index(fields=['profile', '-start_date'], name='resume_expe_profile_d29e55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certification or course name (max 200 characters)', max_length=200, verbose_name='Certification Name')),
                ('provider', models.CharField(help_text='Issuing organization or platform (max 200 characters)', max_length=200, verbose_name='Provider/Organization')),
                ('date_obtained', models.DateField(blank=True, help_text='Date when certification was obtained (optional)', null=True, verbose_name='Date Obtained')),
                ('credential_url', models.URLField(blank=True, help_text='URL to verify credential (optional)', verbose_name='Credential URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-date_obtained'],
                'indexes': [models.Index(fields=['profile', 'order'], name='resume_cert_profile_796968_idx')],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief achievement title (max 200 characters)', max_length=200, verbose_name='Achievement Title')),
                ('description', models.TextField(help_text='Detailed achievement description', verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Icon name for visual display (optional, e.g., 'trophy', 'star')", max_length=50, verbose_name='Icon Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='resume.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['profile', 'order'], name='resume_achi_profile_11d0c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill or technology name (max 100 characters)', max_length=100, verbose_name='Skill Name')),
                ('category', models.CharField(blank=True, help_text='Skill category for grouping (optional)', max_length=100, verbose_name='Category')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'category', 'name'],
                'indexes': [models.Index(fields=['profile', 'order'], name='resume_skil_profile_de0329_idx'), models.Index(fields=['profile', 'category'], name='resume_skil_profile_14a22c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_skill_per_profile'),
        ),
    ]
